MF-383 : Implemented carbon styled vitals chart view
openmrs/openmrs-esm-patient-chart-widgets pull request #172
Opened 2020-12-15 14:10 UTC by donaldkibet

### What does this PR do?

It implements vitals widget chart view

### Screenshot
![vitals-chart](https://user-images.githubusercontent.com/28008754/102225313-23e5b400-3ef8-11eb-8805-0a0e4ef1f7b0.gif)

2020-12-16 19:35 UTC, jonathandick commented
@nmalyschkin are you able to review?

2020-12-17 13:50 UTC, nmalyschkin requested changes

2020-12-17 13:50 UTC, nmalyschkin commented on src/widgets/vitals/vitals-chart.component.tsx
> +      .sort((a: any, b: any) => b.date - a.date);
Seems to me that this `sort` would have no effect, since there is no `date` attribute. Was the sort operation supposed to be done before the mapping?

2020-12-28 14:54 UTC, jonathandick commented
I"m going to merge this as the issue appears to have been addressed by latest commit.

2020-12-28 14:54 UTC, merged