Start visit
openmrs/openmrs-esm-patient-chart-widgets pull request #45
Opened 2020-04-22 14:33 UTC by nkimaina

2020-04-24 13:22 UTC, FlorianRappl requested changes
I think we are on a great track here. Thanks for the work!

2020-04-24 13:22 UTC, FlorianRappl commented on src/utils/use-session-user.tsx
> +    return () => currentUserSub.unsubscribe();
This will fail - currentUserSub may (i.e., will) be undefined

2020-04-24 13:22 UTC, FlorianRappl commented on src/utils/use-session-user.tsx
> +      openmrsObservableFetch("/ws/rest/v1/session").subscribe(user => {
I think you want to set `currentUserSub` here, right?

2020-04-24 13:22 UTC, FlorianRappl commented on src/widgets/location/location-select.component.tsx
> +    <>
Is the fragment really necessary in this case? There is just one child element.

2020-04-24 13:22 UTC, FlorianRappl commented on src/widgets/location/location-select.component.tsx
> +          {""}
I think this is the same as `<option value="" className="omrs-padding-8" />`

2020-04-24 13:22 UTC, FlorianRappl commented on src/widgets/location/use-locations.tsx
> +    let locationSub: Subscription;
Why not just `const locationSub = ...`? I think the typing would also benefit (no need for the explicit `Subscription`)

2020-04-24 13:22 UTC, FlorianRappl commented on src/widgets/visit/use-started-visit.tsx
> +  const [startedVisit, setStartedVisit] = useState(undefined);
`useState<?>(undefined)` - what is it?

2020-04-24 13:22 UTC, FlorianRappl commented on src/widgets/visit/use-visit-types.tsx
> +    visitTypesSub = getVisitTypes().subscribe(
See above - just assign in initialization.

2020-04-24 13:22 UTC, FlorianRappl commented on src/widgets/visit/visit-type-select.component.tsx
> +          {""}
Same as above.

2020-04-27 14:33 UTC, nkimaina commented
@FlorianRappl Sorry that these changes are a lot to review, we are transferring this functionality from an internal repo. Also, we've not had a design session to agree on how visits should function, but these are standard features that will most likely be needed when we have the design.

2020-04-28 08:25 UTC, donaldkibet approved these changes
lgtm

2020-04-28 08:53 UTC, merged